/** Button icons from Lucide, behind one component so screens name them by role. */
import {
  ArrowLeft,
  ArrowRight,
  Check,
  ChevronDown,
  CircleStop,
  UserX,
  ChevronUp,
  Crown,
  Eraser,
  ExternalLink,
  Eye,
  EyeOff,
  Flag,
  Hand,
  Info,
  Keyboard,
  Link,
  Minus,
  Paintbrush,
  Pencil,
  Play,
  Plus,
  Redo2,
  RotateCcw,
  Share2,
  Trash2,
  Undo2,
  Users,
  Volume2,
  VolumeX,
  type LucideProps,
} from "lucide-preact";
import type { FunctionComponent } from "preact";

const ICONS = {
  hand: Hand,
  brush: Paintbrush,
  eraser: Eraser,
  trash: Trash2,
  check: Check,
  info: Info,
  keyboard: Keyboard,
  next: ArrowRight,
  back: ArrowLeft,
  flag: Flag,
  link: Link,
  external: ExternalLink,
  play: Play,
  refresh: RotateCcw,
  undo: Undo2,
  edit: Pencil,
  redo: Redo2,
  crown: Crown,
  kick: UserX,
  stop: CircleStop,
  users: Users,
  eye: Eye,
  eyeOff: EyeOff,
  expand: ChevronDown,
  collapse: ChevronUp,
  minus: Minus,
  plus: Plus,
  share: Share2,
  soundOn: Volume2,
  soundOff: VolumeX,
} satisfies Record<string, FunctionComponent<LucideProps>>;

export type IconName = keyof typeof ICONS;

export function Icon({ name, size = 16 }: { name: IconName; size?: number }) {
  const Glyph = ICONS[name];
  return <Glyph class="icon" size={size} strokeWidth={2} aria-hidden="true" />;
}
